### ISSUE TITLE
issues running the tool

### ISSUE THREAD

**Issue by tarek-bochkati** [Jegeva/ads2svd#1]
Hi @Jegeva 

Thanks for the tool.

I have tried to generate the SVD files using the provided Makefile.
using Python2 (I tried 3 too) but I got the following error:
Please advise :)
```
python3 ./ads2svd.py -c ./in -i in/Cores/Cortex-M23.xml
python3 ./ads2svd.py -c ./in -i in/Cores/Cortex-A73.xml
python3 ./ads2svd.py -c ./in -i in/Cores/AEMv8M_FVP.xml
python3 ./ads2svd.py -c ./in -i in/Cores/ARM966E-S.xml
Traceback (most recent call last):
Traceback (most recent call last):
  File "./ads2svd.py", line 112, in <module>
  File "./ads2svd.py", line 112, in <module>
    build_schema_wrapper()
  File "./ads2svd.py", line 48, in build_schema_wrapper
    build_schema_wrapper()
    s  = etree.XMLSchema(etree.XML(ws))
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
  File "./ads2svd.py", line 48, in build_schema_wrapper
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}specialAttrs' does not resolve to a(n) attribute group definition., line 28
    s  = etree.XMLSchema(etree.XML(ws))
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}specialAttrs' does not resolve to a(n) attribute group definition., line 28
Traceback (most recent call last):
  File "./ads2svd.py", line 112, in <module>
Traceback (most recent call last):
    build_schema_wrapper()
  File "./ads2svd.py", line 112, in <module>
  File "./ads2svd.py", line 48, in build_schema_wrapper
    build_schema_wrapper()
    s  = etree.XMLSchema(etree.XML(ws))
  File "./ads2svd.py", line 48, in build_schema_wrapper
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
    s  = etree.XMLSchema(etree.XML(ws))
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}specialAttrs' does not resolve to a(n) attribute group definition., line 28
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}specialAttrs' does not resolve to a(n) attribute group definition., line 28
Makefile:22: recipe for target 'out/AEMv8M_FVP.xml' failed
make: *** [out/AEMv8M_FVP.xml] Error 1
make: *** Waiting for unfinished jobs....
Makefile:22: recipe for target 'out/Cortex-M23.xml' failed
make: *** [out/Cortex-M23.xml] Error 1
Makefile:22: recipe for target 'out/Cortex-A73.xml' failed
make: *** [out/Cortex-A73.xml] Error 1
Makefile:22: recipe for target 'out/ARM966E-S.xml' failed
make: *** [out/ARM966E-S.xml] Error 1
```

**Comment by Jegeva** [comment]
Hello tarek,

it is python3 indeed
i have lxml 4.5.0 installed from pip3, it works locally, maybe it is from lxml ?
$pip3 install lxml ?
can you try to update lxml ? 
also remove the MAKEFLAGS += --jobs=$(PROCS) in the makefile to make it clearer please

**Comment by tarek-bochkati** [comment]
thanks @Jegeva for your quick response :)

I have already lxml-4.5.0 installed using pip3, and forced the python3 in the Makefile:
```makefile
IN_DIR=in/Cores
OUT_DIR=out
IN_FILES=$(wildcard $(IN_DIR)/*.xml)
OUT_FILES=$(IN_FILES:$(IN_DIR)/%.xml=$(OUT_DIR)/%.svd)
INTER_FILES=$(IN_FILES:$(IN_DIR)/%.xml=$(OUT_DIR)/%.xml)

SAXONHE_PATH=saxon9he.jar

XLST_FILE=./ads2svd.xslt

#$(info OUTFILES   $(OUT_FILES) )

.PHONY: clean all
#uncomment to keep the intermediate xml files
.SECONDARY: $(INTER_FILES)

all: $(OUT_DIR) $(OUT_FILES)

$(OUT_DIR)/%.xml : $(IN_DIR)/%.xml
	python3 ./ads2svd.py -c ./in -i $<		

$(OUT_DIR)/%.svd : $(OUT_DIR)/%.xml $(XLST_FILE)
	java -jar $(SAXONHE_PATH) -xsl:$(XLST_FILE) -s:$< -o:$@

clean:
	rm out/*
```

now the log is quite simpler:
```
.../Projects/svd/ads2svd-master-head$ make
python3 ./ads2svd.py -c ./in -i in/Cores/Cortex-M23.xml
Traceback (most recent call last):
  File "./ads2svd.py", line 112, in <module>
    build_schema_wrapper()
  File "./ads2svd.py", line 48, in build_schema_wrapper
    s  = etree.XMLSchema(etree.XML(ws))
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}specialAttrs' does not resolve to a(n) attribute group definition., line 28
Makefile:22: recipe for target 'out/Cortex-M23.xml' failed
make: *** [out/Cortex-M23.xml] Error 1
```
any idea ?

Thanks in advance,
Tarek

**Comment by tarek-bochkati** [comment]
One more thing I have saved the ws schema generated in build_schema_wrapper
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="">
  <xs:import namespace="http://com.arm.targetconfigurationeditor" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/board-01.xsd" />
  <xs:import namespace="http://com.arm.targetconfigurationeditor" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/board.xsd" />
  <xs:import namespace="http://www.arm.com/cdb_config" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/cdb_config.xsd" />
  <xs:import namespace="http://www.arm.com/core_contents" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/core_contents.xsd" />
  <xs:import namespace="http://www.arm.com/Core_CP15" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/Core_CP15_Regs.xsd" />
  <xs:import namespace="http://www.arm.com/core_definition" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/core_definition.xsd" />
  <xs:import namespace="http://www.arm.com/core_reg" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/core_register_definition.xsd" />
  <xs:import namespace="http://www.arm.com/flash_config" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/flash_config.xsd" />
  <xs:import namespace="http://www.arm.com/model_desc_file" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/mdfschema.xsd" />
  <xs:import namespace="http://www.arm.com/project_type" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/platform_data-1.xsd" />
  <xs:import namespace="http://www.arm.com/project_type" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/platform_data.xsd" />
  <xs:import namespace="http://www.arm.com/probe" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/probeschema.xsd" />
  <xs:import namespace="http://www.arm.com/soc_definition" schemaLocation="file:///mnt/c/Projects/svd/ads2svd-master-head/in/Schemas/soc_definition.xsd" />
</xs:schema>
```

to get it working I commented the call to build_schema_wrapper in line 112.
but IDK if this is a good way to proceed.

**Comment by jwinarske** [comment]
@tarek-bochkati  You might want to see if my PR addresses the issue:  https://github.com/Jegeva/ads2svd/pull/3

**Comment by Jegeva** [comment]
hello tarek, sorry for the delay but covid blah blah blah.

1) no need to force python3 in the makefile, the first line of ads2svd.py does it already
2) Normally we should validate the xml against a schema so removing the validation wrapper isn't perfect

hum are you doing this on an offline machine by any chance ? (cf.https://mailman-mail5.webfaction.com/pipermail/lxml/20150225/015354.html)

**Comment by tarek-bochkati** [comment]
@Jegeva , I don't remember if I was offline
I will recheck and let you know.

Thanks,
Tarek
